"""Compile Classic SpellName CSV exports into per-flavor aura alias catalogs.

Classic aura payloads carry rank-specific spell IDs (Vanilla, TBC) or a
different aura ID than the cast (Mists). The Classic backend therefore expands
every configured, curated or indicator spell ID to all IDs that share its exact
localized SpellName, the same way WeakAuras matches auras by name on Classic.

Input: one <locale>/SpellName.csv per supported locale exported from the
flavor's own client build (wago.tools DB2 CSV export of SpellName, FileDataID
1990283). The encoding, loader (MSUF_Auras3_AuraAliases.lua) and file naming
are identical to Retail's .github/scripts/generate_aura_alias_catalog.py; only
the row-count sanity floor and the header differ, because Classic builds ship
roughly 30k spell names instead of Retail's 400k+.

Usage (run from the Classic repository root):
  python .github/scripts/generate_classic_aura_alias_catalog.py \
      --flavor Vanilla --build 1.15.9.68940 --input <dir-with-locale-folders>
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import defaultdict
from pathlib import Path

LOCALES = ("enUS", "deDE", "frFR", "esES", "esMX", "itIT", "ptBR", "ruRU", "koKR", "zhCN", "zhTW")
FLAVORS = ("Vanilla", "TBC", "Mists")
DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
WIDTH = 4
MIN_ROWS = 20_000


def encode(value: int) -> str:
    if not 0 < value < 36 ** WIDTH:
        raise ValueError(f"Spell ID outside catalog encoding: {value}")
    result = ""
    for _ in range(WIDTH):
        value, digit = divmod(value, 36)
        result = DIGITS[digit] + result
    return result


def read_groups(path: Path) -> tuple[set[tuple[int, ...]], dict]:
    names = defaultdict(list)
    ids = set()
    with path.open(encoding="utf-8-sig", newline="") as source:
        reader = csv.DictReader(source)
        if reader.fieldnames != ["ID", "Name_lang"]:
            raise ValueError(f"Unexpected SpellName columns in {path}: {reader.fieldnames}")
        for row in reader:
            spell_id = int(row["ID"])
            encode(spell_id)
            if spell_id in ids:
                raise ValueError(f"Duplicate SpellName ID: {spell_id}")
            ids.add(spell_id)
            if row["Name_lang"]:
                names[row["Name_lang"]].append(spell_id)
    if len(ids) < MIN_ROWS:
        raise ValueError(f"Incomplete Classic SpellName export: {path} ({len(ids)} rows)")
    groups = {tuple(sorted(group)) for group in names.values() if len(group) > 1}
    return groups, {"csv_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "rows": len(ids), "groups": len(groups),
                    "alias_ids": sum(map(len, groups)), "max_id": max(ids)}


def pack(groups: set[tuple[int, ...]]) -> str:
    return "\n" + "\n".join("".join("_" + encode(i) for i in group)
                               for group in sorted(groups)) + "\n"


def unpack(blob: str) -> set[tuple[int, ...]]:
    return {tuple(int(token, 36) for token in row.split("_")[1:])
            for row in blob.splitlines() if row}


def generate(inputs: Path, output: Path, flavor: str, build: str) -> dict:
    groups, provenance = {}, {}
    for locale in LOCALES:
        csv_path = inputs / locale / "SpellName.csv"
        groups[locale], provenance[locale] = read_groups(csv_path)
    row_counts = {p["rows"] for p in provenance.values()}
    if len(row_counts) != 1:
        raise ValueError(f"Locale exports disagree on row count: {row_counts}")
    common = set.intersection(*groups.values())
    output.mkdir(parents=True, exist_ok=True)
    files = {}
    for locale in ("Common",) + LOCALES:
        selected = common if locale == "Common" else groups[locale] - common
        blob = pack(selected)
        assert unpack(blob) == selected
        if locale != "Common":
            assert common | unpack(blob) == groups[locale]
            assert not {i for g in common for i in g}.intersection(i for g in selected for i in g)
        header = ("-- GENERATED by .github/scripts/generate_classic_aura_alias_catalog.py; do not edit.\n"
                  f"-- SpellName / Classic {flavor} {build} / {locale}; exact-name groups, base36 IDs.\n"
                  "local _, MSUF = ...\n")
        if locale != "Common":
            header += ("local locale = GetLocale()\n"
                       "if locale == \"enGB\" then locale = \"enUS\" end\n"
                       "if locale == \"ptPT\" then locale = \"ptBR\" end\n"
                       f'if locale ~= "{locale}" then return end\n')
        field = "common" if locale == "Common" else "localized"
        if locale == "Common":
            header += f'MSUF.MSUF_Auras3.AuraAliasCatalog = {{ build = "{flavor}-{build}", width = {WIDTH} }}\n'
        else:
            header += "MSUF.MSUF_Auras3.AuraAliasCatalog.locale = locale\n"
        source = header + f"MSUF.MSUF_Auras3.AuraAliasCatalog.{field} = [[\n" + blob + "]]\n"
        filename = f"MSUF_Auras3_AliasData_{locale}.lua"
        (output / filename).write_text(source, encoding="ascii", newline="\n")
        files[filename] = {"bytes": len(source), "sha256": hashlib.sha256(source.encode()).hexdigest()}
    return {"flavor": flavor, "build": build, "file_data_id": 1990283,
            "encoding": "base36-token-groups-v1", "common_groups": len(common),
            "locales": provenance, "generated": files}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--flavor", choices=FLAVORS, required=True)
    parser.add_argument("--build", required=True, help="client build, e.g. 1.15.9.68940")
    parser.add_argument("--input", type=Path, required=True, help="directory holding <locale>/SpellName.csv")
    parser.add_argument("--output", type=Path, default=None,
                        help="defaults to MidnightSimpleUnitFrames/Game/<flavor>/Auras/AliasData")
    parser.add_argument("--manifest", type=Path, default=None,
                        help="defaults to .github/auras3-alias-catalog-<flavor>.json")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    output = args.output or root / "MidnightSimpleUnitFrames" / "Game" / args.flavor / "Auras" / "AliasData"
    manifest_path = args.manifest or root / ".github" / f"auras3-alias-catalog-{args.flavor.lower()}.json"
    manifest = generate(args.input, output, args.flavor, args.build)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"{args.flavor} {args.build}: verified all 11 locale partitions; "
          f"{manifest['common_groups']} shared groups; "
          f"{sum(f['bytes'] for f in manifest['generated'].values()):,} generated bytes -> {output}")


if __name__ == "__main__":
    main()
