"""Compile SpellName CSV exports into cold-path, locale-exact aura aliases.

Input: DBC2CSV exports of FileDataID 1990283, one <locale>/SpellName.csv per
supported locale. Apply same-build DBCache.bin to the relevant locale BEFORE
exporting. Never guess translations, filter by player spells, or cap a group.
Only exact, nonempty name equality creates aliases. Output contains IDs only.
See .github/AURAS3_ALIAS_CATALOG.md for the reproducible extraction procedure.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import struct
from collections import defaultdict
from pathlib import Path

LOCALES = ("enUS", "deDE", "frFR", "esES", "esMX", "itIT", "ptBR", "ruRU", "koKR", "zhCN", "zhTW")
DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
WIDTH = 4


def encode(value: int) -> str:
    if not 0 < value < 36 ** WIDTH:
        raise ValueError(f"Spell ID outside catalog encoding: {value}")
    result = ""
    for _ in range(WIDTH):
        value, digit = divmod(value, 36)
        result = DIGITS[digit] + result
    return result


def read_groups(path: Path) -> tuple[set[tuple[int, ...]], dict]:
    names = defaultdict(list)
    ids = set()
    with path.open(encoding="utf-8-sig", newline="") as source:
        reader = csv.DictReader(source)
        if reader.fieldnames != ["ID", "Name_lang"]:
            raise ValueError(f"Unexpected SpellName columns: {reader.fieldnames}")
        for row in reader:
            spell_id = int(row["ID"])
            encode(spell_id)  # Validate every row, including singleton names.
            if spell_id in ids:
                raise ValueError(f"Duplicate SpellName ID: {spell_id}")
            ids.add(spell_id)
            if row["Name_lang"]:
                names[row["Name_lang"]].append(spell_id)
    if len(ids) < 400_000:
        raise ValueError(f"Incomplete Retail SpellName export: {path} ({len(ids)} rows)")
    groups = {tuple(sorted(group)) for group in names.values() if len(group) > 1}
    return groups, {"csv_sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "rows": len(ids), "groups": len(groups),
                    "alias_ids": sum(map(len, groups)), "max_id": max(ids)}


def pack(groups: set[tuple[int, ...]]) -> str:
    # Tokens have a distinct prefix and fixed width: an exact C string.find
    # cannot confuse 12 with 123 or match across two adjacent IDs. Newlines
    # delimit groups; each ID occurs once within one locale's combined data.
    return "\n" + "\n".join("".join("_" + encode(i) for i in group)
                               for group in sorted(groups)) + "\n"


def unpack(blob: str) -> set[tuple[int, ...]]:
    return {tuple(int(token, 36) for token in row.split("_")[1:])
            for row in blob.splitlines() if row}


def generate(inputs: Path, output: Path, build: str) -> dict:
    cache = inputs / "DBCache.bin"
    if cache.exists():
        header = cache.read_bytes()[:12]
        magic, _, cache_build = struct.unpack("<4sII", header)
        if magic != b"XFTH" or cache_build != int(build.rsplit(".", 1)[-1]):
            raise ValueError("DBCache header/build does not match the requested catalog")
    groups, provenance = {}, {}
    for locale in LOCALES:
        # An explicitly exported, locale-specific hotfix view takes precedence.
        fixed = inputs / (locale + "-hotfix") / "SpellName.csv"
        csv_path = fixed if fixed.exists() else inputs / locale / "SpellName.csv"
        groups[locale], provenance[locale] = read_groups(csv_path)
        provenance[locale]["hotfixed"] = fixed.exists()
        db2 = inputs / locale / "SpellName.db2"
        if db2.exists():
            provenance[locale]["db2_sha256"] = hashlib.sha256(db2.read_bytes()).hexdigest()
    common = set.intersection(*groups.values())
    output.mkdir(parents=True, exist_ok=True)
    files = {}
    for locale in ("Common",) + LOCALES:
        selected = common if locale == "Common" else groups[locale] - common
        blob = pack(selected)
        assert unpack(blob) == selected
        if locale != "Common":
            assert common | unpack(blob) == groups[locale]
            assert not {i for g in common for i in g}.intersection(i for g in selected for i in g)
        header = ("-- GENERATED by .github/scripts/generate_aura_alias_catalog.py; do not edit.\n"
                  f"-- SpellName / Retail {build} / {locale}; exact-name groups, base36 IDs.\n"
                  "local _, MSUF = ...\n")
        if locale != "Common":
            header += ("local locale = GetLocale()\n"
                       "if locale == \"enGB\" then locale = \"enUS\" end\n"
                       "if locale == \"ptPT\" then locale = \"ptBR\" end\n"
                       f'if locale ~= "{locale}" then return end\n')
        field = "common" if locale == "Common" else "localized"
        if locale == "Common":
            header += f'MSUF.MSUF_Auras3.AuraAliasCatalog = {{ build = "{build}", width = {WIDTH} }}\n'
        else:
            header += "MSUF.MSUF_Auras3.AuraAliasCatalog.locale = locale\n"
        # An extra newline is necessary: Lua discards the first newline after [[.
        source = header + f"MSUF.MSUF_Auras3.AuraAliasCatalog.{field} = [[\n" + blob + "]]\n"
        filename = f"MSUF_Auras3_AliasData_{locale}.lua"
        (output / filename).write_text(source, encoding="ascii", newline="\n")
        files[filename] = {"bytes": len(source), "sha256": hashlib.sha256(source.encode()).hexdigest()}
    manifest = {"build": build, "file_data_id": 1990283, "encoding": "base36-token-groups-v1",
                "common_groups": len(common), "locales": provenance, "generated": files}
    if cache.exists():
        manifest["hotfix_sha256"] = hashlib.sha256(cache.read_bytes()).hexdigest()
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--build", required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    manifest = generate(args.input, args.output, args.build)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Verified all 11 locale partitions; {manifest['common_groups']} shared groups; "
          f"{sum(f['bytes'] for f in manifest['generated'].values()):,} generated bytes")


if __name__ == "__main__":
    main()
