"""The Classic Assistant control schema is data under review, and it says so.

MSUF_AssistantControlSchema_Data_Classic.lua ships with the Classic Assistant and is
what the Assistant matches a spoken control name against. It used to open with
"Generated by tools/generate_assistant_control_schema.ps1. Do not edit by hand." -
a script that is not in this repository, so nothing here could reproduce or check it,
and no gate step read the file at all.

Two things are pinned instead.

1. No tracked Classic-owned file may claim a generator this repository does not
   contain. Retail-mapped addon paths are exempt: their header describes Retail's
   tooling and the Classic tree must keep their bytes.

2. The schema's control ids are compared against the controls the Classic menu
   really builds. The proxy for "the Classic menu builds it" is the generated
   Menu2 search index for the Classic clients, which is produced by an actual
   headless build of every Classic page (see CLASSIC_PROTOTYPE.md) and whose
   freshness against the Menu2 sources is enforced by
   .github/scripts/menu2_search_index_hash_smoke.py in this same gate. The
   menu_chrome page is excluded on both sides: the generator cannot build it, so
   its index rows are schema stand-ins and comparing them would be circular.

The schema is a snapshot and the index is the union over the Classic flavors, so the
two do not match exactly. The divergence is therefore recorded, not assumed away: the
counts and a digest of the sorted id lists are pinned below. Any Menu2 change that
adds, removes or renames a control moves one of them and turns this smoke red, which
is the point - the schema then gets a conscious update (or the ledger does, with the
new numbers printed by the failure).
"""
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(sys.argv[1]).resolve()
SCHEMA = "MidnightSimpleUnitFrames_Assistant/Assistant/MSUF_AssistantControlSchema_Data_Classic.lua"
INDEX = "MidnightSimpleUnitFrames_Options/Shell/Menu2/Search/MSUF_Menu2_Search_StaticIndex_Data_Classic.lua"
OWNED = "tools/classic-owned-addon-paths.txt"
ADDON_FOLDERS = ("MidnightSimpleUnitFrames/", "MidnightSimpleUnitFrames_Options/",
                 "MidnightSimpleUnitFrames_Assistant/")
UNIT_SEPARATOR = chr(31)
CLAIM = re.compile(r"--\s*Generated by ([^\s,;]+?)\.?\s")
CONTROL_ID = re.compile(r"^menu2\.[A-Za-z0-9_@:%./+-]+$")
CLASSIFICATIONS = {"setting", "action", "ephemeral", "navigation"}
EXCLUDED_PAGE = "menu_chrome"

# Reviewed on 2026-09-20 against the Classic search index of the same commit.
LEDGER = {
    "records": 3476,
    "columns": 31,
    "schemaOnly": (298, "9022F4DE2CD5FF16DF75619E18FE945022316AC34AA589B6CC6CB284F317D077"),
    # Appearance preset and background opacity are now offered on Classic too.
    "indexOnly": (560, "A68DA8265690E81373FDD749773C86185BB73B202C1264FBFAE60591AC4AE880"),
}


def fail(*detail):
    raise SystemExit("Classic Assistant control schema contract failed: "
                     + " | ".join(str(part) for part in detail))


def read(relative):
    path = ROOT / relative
    if not path.is_file():
        fail("missing file:", relative)
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")


def digest(values):
    return hashlib.sha256("\n".join(values).encode("utf-8")).hexdigest().upper()


def tracked_paths():
    result = subprocess.run(["git", "-C", str(ROOT), "ls-files"],
                            capture_output=True, check=False)
    if result.returncode != 0:
        fail("git ls-files failed:", result.stderr.decode("utf-8", "replace").strip())
    return [line.replace("\\", "/") for line in
            result.stdout.decode("utf-8").splitlines() if line.strip()]


# ---------------------------------------------------------------- 1. honest headers
tracked = tracked_paths()
trackedSet = set(tracked)
owned = {line.strip() for line in read(OWNED).splitlines() if line.strip() and not line.startswith("#")}
checked, claims = 0, 0
for relative in tracked:
    if relative.startswith(ADDON_FOLDERS) and relative not in owned:
        continue  # a Retail-mapped path: its header describes Retail's tooling
    if not relative.endswith((".lua", ".py", ".ps1", ".tsv", ".txt")):
        continue
    path = ROOT / relative
    if not path.is_file():
        continue
    checked += 1
    head = "\n".join(path.read_text(encoding="utf-8-sig", errors="replace")
                     .replace("\r\n", "\n").split("\n")[:6])
    claim = CLAIM.search(head + "\n")
    if not claim:
        continue
    claims += 1
    generator = claim.group(1).replace("\\", "/")
    if generator not in trackedSet:
        fail(relative, "claims it is generated by", generator,
             "but no such file is tracked in this repository;",
             "either track the generator or stop claiming the file is generated")
print(f"PASS generator claims: {claims} of {checked} tracked Classic-owned files claim a "
      f"generator, and every claimed generator is tracked")

# ---------------------------------------------------------------- 2. schema shape
text = read(SCHEMA)
if "Generated by" in text.split("local _, MSUF", 1)[0]:
    fail(SCHEMA, "still opens with a 'Generated by' claim; this file is reviewed data")
columns = re.search(r"Data\.columns = \{(.*?)\}", text, re.S)
if not columns:
    fail(SCHEMA, "declares no Data.columns")
columnNames = [name.strip().strip("'") for name in columns.group(1).split(",") if name.strip()]
if len(columnNames) != LEDGER["columns"]:
    fail(SCHEMA, "declares", len(columnNames), "columns; the ledger records", LEDGER["columns"])
for required in ("controlId", "pageKey", "classification"):
    if required not in columnNames:
        fail(SCHEMA, "has no column", required)
controlIndex = columnNames.index("controlId")
pageIndex = columnNames.index("pageKey")
classIndex = columnNames.index("classification")

if "Data.records = {" not in text:
    fail(SCHEMA, "declares no Data.records")
records = []
for line in text.split("Data.records = {", 1)[1].split("\n"):
    line = line.strip()
    if not line.startswith("{ '"):
        continue
    records.append(re.findall(r"'((?:[^'\\]|\\.)*)'", line))
if len(records) != LEDGER["records"]:
    fail(SCHEMA, "carries", len(records), "records; the ledger records", LEDGER["records"])
widths = {len(record) for record in records}
if widths != {len(columnNames)}:
    fail(SCHEMA, "rows are not all", len(columnNames), "fields:", sorted(widths))

seen = set()
for record in records:
    controlId = record[controlIndex]
    if not CONTROL_ID.match(controlId):
        fail(SCHEMA, "row has a malformed control id:", repr(controlId))
    if controlId in seen:
        fail(SCHEMA, "two rows share a control id:", controlId)
    seen.add(controlId)
    if record[classIndex] not in CLASSIFICATIONS:
        fail(SCHEMA, "row has an unknown classification:", repr(record[classIndex]))
print(f"PASS schema shape: {len(records)} records of {len(columnNames)} fields, "
      f"{len(seen)} unique control ids, classifications within {sorted(CLASSIFICATIONS)}")

# ---------------------------------------------------------------- 3. built-control ledger
blob = read(INDEX)
if "Search.StaticIndexBlob = [==[\n" not in blob:
    fail(INDEX, "has no blob; the Menu2 search index is the built-control reference")
rowsText = blob.split("Search.StaticIndexBlob = [==[\n", 1)[1].rsplit("\n]==]\n", 1)[0]
built = set()
for row in rowsText.split("\n"):
    if not row:
        continue
    fields = row.split("\t")
    if len(fields) != 12:
        fail(INDEX, "row is not 12 fields:", repr(row[:120]))
    if fields[0] == EXCLUDED_PAGE:
        continue
    parts = fields[7].split(UNIT_SEPARATOR)
    if parts[0] != "id" or len(parts) < 3:
        fail(INDEX, "row identity carries no control id:", repr(fields[7]))
    built.add(parts[2].replace("%2E", ".").replace("%1F", UNIT_SEPARATOR).replace("%25", "%"))
if not built:
    fail(INDEX, "names no built control")

schemaActionable = {record[controlIndex] for record in records
                    if record[classIndex] in ("setting", "action") and record[pageIndex] != EXCLUDED_PAGE}
schemaAll = {record[controlIndex] for record in records if record[pageIndex] != EXCLUDED_PAGE}
schemaOnly = sorted(schemaActionable - built)
indexOnly = sorted(built - schemaAll)

for label, actual, recorded, remedy in (
    ("schemaOnly", schemaOnly, LEDGER["schemaOnly"],
     "schema rows name a control the Classic menu no longer builds"),
    ("indexOnly", indexOnly, LEDGER["indexOnly"],
     "controls the Classic menu builds have no schema row"),
):
    count, recordedDigest = recorded
    actualDigest = digest(actual)
    if len(actual) != count or actualDigest != recordedDigest:
        sample = ", ".join(actual[:6]) or "(none)"
        fail(label, remedy + ":", "recorded", count, recordedDigest[:16],
             "but found", len(actual), actualDigest[:16],
             "- review the change, then update LEDGER in this smoke.",
             "First entries:", sample)
print(f"PASS built-control ledger: {len(schemaActionable)} actionable schema controls vs "
      f"{len(built)} built controls; {len(schemaOnly)} schema-only and {len(indexOnly)} "
      f"index-only ids match the reviewed ledger")
