local addonName, MSUF = ...
MSUF = MSUF or {}

local M = MSUF.MSUF2 or {}
MSUF.MSUF2 = M
_G.MSUF2 = M

local Data = M.SearchData or {}
M.SearchData = Data

Data.TEXT_FOLDS = {
    ["\195\128"] = "a", ["\195\129"] = "a", ["\195\130"] = "a", ["\195\131"] = "a", ["\195\133"] = "a",
    ["\195\160"] = "a", ["\195\161"] = "a", ["\195\162"] = "a", ["\195\163"] = "a", ["\195\165"] = "a",
    ["\195\135"] = "c", ["\195\167"] = "c",
    ["\195\136"] = "e", ["\195\137"] = "e", ["\195\138"] = "e", ["\195\139"] = "e",
    ["\195\168"] = "e", ["\195\169"] = "e", ["\195\170"] = "e", ["\195\171"] = "e",
    ["\195\140"] = "i", ["\195\141"] = "i", ["\195\142"] = "i", ["\195\143"] = "i",
    ["\195\172"] = "i", ["\195\173"] = "i", ["\195\174"] = "i", ["\195\175"] = "i",
    ["\195\145"] = "n", ["\195\177"] = "n",
    ["\195\146"] = "o", ["\195\147"] = "o", ["\195\148"] = "o", ["\195\149"] = "o",
    ["\195\178"] = "o", ["\195\179"] = "o", ["\195\180"] = "o", ["\195\181"] = "o",
    ["\195\153"] = "u", ["\195\154"] = "u", ["\195\155"] = "u",
    ["\195\185"] = "u", ["\195\186"] = "u", ["\195\187"] = "u",
}

Data.UTF_PUNCTUATION = {
    "\194\160", --- nbsp
    "\226\128\152", "\226\128\153", "\226\128\156", "\226\128\157",
    "\226\128\147", "\226\128\148", "\226\128\166",
    "\227\128\129", "\227\128\130",
    "\239\188\129", "\239\188\140", "\239\188\154", "\239\188\155", "\239\188\159",
}

Data.NOISE_TEXT = {
    [""] = true,
    ["x"] = true,
    ["+"] = true,
    ["-"] = true,
    ["<"] = true,
    [">"] = true,
    ["|"] = true,
}

Data.STOP_WORDS = {
    a = true,
    an = true,
    ["and"] = true,
    are = true,
    bother = true,
    bothering = true,
    can = true,
    cant = true,
    change = true,
    changed = true,
    changing = true,
    configure = true,
    configured = true,
    customize = true,
    customise = true,
    ["do"] = true,
    does = true,
    doesnt = true,
    didn = true,
    didnt = true,
    basically = true,
    blind = true,
    brain = true,
    find = true,
    fixed = true,
    fix = true,
    ["for"] = true,
    get = true,
    going = true,
    hey = true,
    help = true,
    how = true,
    i = true,
    im = true,
    ["in"] = true,
    is = true,
    it = true,
    just = true,
    m = true,
    make = true,
    maybe = true,
    my = true,
    need = true,
    now = true,
    ["not"] = true,
    of = true,
    on = true,
    ["or"] = true,
    please = true,
    pls = true,
    option = true,
    options = true,
    de = true,
    del = true,
    el = true,
    la = true,
    las = true,
    los = true,
    un = true,
    una = true,
    esta = true,
    este = true,
    donde = true,
    como = true,
    est = true,
    le = true,
    les = true,
    des = true,
    du = true,
    une = true,
    ou = true,
    il = true,
    lo = true,
    gli = true,
    di = true,
    da = true,
    dove = true,
    per = true,
    para = true,
    o = true,
    os = true,
    as = true,
    um = true,
    uma = true,
    onde = true,
    ["найти"] = true,
    ["где"] = true,
    ["как"] = true,
    ["опция"] = true,
    setting = true,
    settings = true,
    setup = true,
    so = true,
    sorry = true,
    thanks = true,
    the = true,
    thx = true,
    to = true,
    want = true,
    where = true,
    why = true,
    with = true,
    would = true,
    t = true,
    etc = true,
    functioning = true,
    n = true,
    wtf = true,
    dumb = true,
    stupid = true,
    plsfix = true,
    s = true,
    see = true,
    image = true,
    screenshot = true,
    happening = true,
    here = true,
    still = true,
    even = true,
    though = true,
    wie = true,
    kann = true,
    ich = true,
    ist = true,
    sind = true,
    das = true,
    die = true,
    der = true,
    den = true,
    dem = true,
    ein = true,
    eine = true,
    einer = true,
    mein = true,
    meine = true,
    nicht = true,
    warum = true,
    wo = true,
    was = true,
    aendern = true,
    andern = true,
    einstellen = true,
    einstellungen = true,
    finde = true,
    finden = true,
    bitte = true,
    du = true,
    fuer = true,
    fur = true,
    mal = true,
    man = true,
    mich = true,
    mir = true,
    mit = true,
    nur = true,
    optionen = true,
    noch = true,
    immer = true,
    aus = true,
    obwohl = true,
    trotzdem = true,
    werden = true,
    und = true,
    oder = true,
    zu = true,
    zur = true,
    zum = true,
}

Data.QUERY_SOFT_STOP_WORDS = {
    activate = true,
    activated = true,
    adjust = true,
    button = true,
    checkbox = true,
    choose = true,
    chosen = true,
    decrease = true,
    disable = true,
    disabled = true,
    dropdown = true,
    enable = true,
    enabled = true,
    hide = true,
    hidden = true,
    increase = true,
    input = true,
    off = true,
    open = true,
    select = true,
    selected = true,
    slider = true,
    switch = true,
    toggle = true,
    turn = true,
    value = true,
    visible = true,
    aktivieren = true,
    aktiviere = true,
    aktiviert = true,
    anpassen = true,
    anzeigen = true,
    ausblenden = true,
    ausschalten = true,
    auswahl = true,
    auswaehlen = true,
    deaktivieren = true,
    deaktiviere = true,
    deaktiviert = true,
    einschalten = true,
    menu = true,
    menue = true,
    regler = true,
    schalter = true,
    umschalter = true,
    choisir = true,
    activer = true,
    desactiver = true,
    seleccionar = true,
    activar = true,
    desactivar = true,
    selezionare = true,
    attivare = true,
    disattivare = true,
    ativar = true,
    desativar = true,
}
