--- Shell/UI/EditMode/MSUF_EditMode_HUD.lua - load-order slot only.
--- The Edit Mode toolbar (MSUF_EditMode_HUD_Kit, _Selection, _Dock, _Picker
--- and MSUF_EditMode_HUD.lua) loads from Shell/EditMode/MSUF_EditMode.xml
--- after the Edit Mode popups it drives. Mainline keeps this Retail path in
--- its load order until the Retail cutover; it defines nothing.
