--- Shell/UI/EditMode/MSUF_EditMode_Layout.lua - load-order slot only.
--- The Edit Mode layout modules (grid, snap, nudge and the drag ticker) load
--- from Shell/EditMode/MSUF_EditMode.xml right after Core, whose Util they
--- read at load. Mainline keeps this Retail path in its load order until the
--- Retail cutover; it defines nothing.
