local e,r,i,n,a,b=_G,math.floor,math.ceil,type,tonumber,tostring
local t
local u={player={w="castbarPlayerBarWidth",h="castbarPlayerBarHeight",x="castbarPlayerOffsetX",y="castbarPlayerOffsetY",detached="castbarPlayerDetached",match="castbarPlayerMatchWidth",enable="enablePlayerCastbar",dx=0,dy=5},target={w="castbarTargetBarWidth",h="castbarTargetBarHeight",x="castbarTargetOffsetX",y="castbarTargetOffsetY",detached="castbarTargetDetached",match="castbarTargetMatchWidth",enable="enableTargetCastbar",dx=65,dy=-15},focus={w="castbarFocusBarWidth",h="castbarFocusBarHeight",x="castbarFocusOffsetX",y="castbarFocusOffsetY",detached="castbarFocusDetached",match="castbarFocusMatchWidth",enable="enableFocusCastbar",dx=65,dy=-15},boss={w="bossCastbarWidth",h="bossCastbarHeight",x="bossCastbarOffsetX",y="bossCastbarOffsetY",detached="bossCastbarDetached",match="bossCastbarMatchWidth",enable="enableBossCastbar",dx=0,dy=0}}local s={unitframe=true,essential=true,utility=true}local P={"player","target","focus","boss"}local A={0.05,0.15,0.35,0.75,1.5,3,5,7}local G=setmetatable({},{__mode="k"})local C,_,o,S,y={},false,false,false,0
local g
local function l(e)e=a(e)or 0 return e>=0 and r(e+0.5)or i(e-0.5)end
local function c()if n(EnsureDB)=="function"then EnsureDB()end return(e.MSUF_DB and e.MSUF_DB.general)or{}end
local function h()t=e.MSUF_UnitFrames or t or e.UnitFrames return t end
local function d()return e.MSUF_InCombat==true or((e.InCombatLockdown and e.InCombatLockdown())and true or false)or((e.UnitAffectingCombat and e.UnitAffectingCombat("player"))and true or false)end
local function i(e)e=b(e or"")return e:match("^boss%d*$")and"boss"or e end
local function U(e)return s[e]and e or nil end
local function M(a,t)local e=e.MSUF_ShouldUseMSUFCastbar if n(e)=="function"then return e(a,t)==true end local e=u[i(a)]return not(e and t and t[e.enable]==false)end
local function s(t,d,o,i,r,a)local e=e.MSUF_SetPointIfChanged if n(e)=="function"then e(t,d,o,i,r,a)return end t:ClearAllPoints();t:SetPoint(d,o,i,l(r),l(a))end
local function F(t,a)if e.MSUF_SetWidthIfChanged then e.MSUF_SetWidthIfChanged(t,a)else t:SetWidth(a)end end
local function H(a,t)if e.MSUF_SetHeightIfChanged then e.MSUF_SetHeightIfChanged(a,t)else a:SetHeight(t)end end
local function p(a,t)if e.MSUF_SetAlphaIfChanged then e.MSUF_SetAlphaIfChanged(a,t)else a:SetAlpha(t)end end
local function f(t)local n=h()t=b(t or"")local a=a(t:match("^boss(%d+)$"))or 1;if i(t)=="boss"then return(n and n["boss"..a])or e["MSUF_boss"..a]or(n and n.boss1)or e.MSUF_boss1 end return(n and n[t])or e["MSUF_"..t]end
local function T(e)local e=f(e)if not e then return nil end local t=e.hpBar or e.healthBar or e.health if t and t.GetWidth and(t:GetWidth()or 0)>0 then return t end return e end
local function h(e,a)if not(e and e.GetWidth)then return nil end local t=e:GetWidth()if not t or t<=0 then return nil end local e=(e.GetEffectiveScale and e:GetEffectiveScale())or 1 local a=(a and a.GetEffectiveScale and a:GetEffectiveScale())or 1;if e<=0 then e=1 end;if a<=0 then a=1 end;return l(e==a and t or t*e/a)end
local function B(e)if e=="utility"then return"UtilityCooldownViewer_AnchorContainer","UtilityCooldownViewer"elseif e=="essential"then return"EssentialCooldownViewer_CDM_Container","EssentialCooldownViewer"end end
local function m(t)return t and(e.MSUF_GetEffectiveCooldownFrame and e.MSUF_GetEffectiveCooldownFrame(t)or e[t])end
local function I(a,t,n)t=U(t)if t=="unitframe"then return h(T(a),n)end local t,a=B(t)local t=h(e[t],n)if not t then t=h(m(a),n)end if not t and a and e[a]~=m(a)then t=h(e[a],n)end return t end
local function r(t,e)local e=u[i(e)]return U(e and t and t[e.match])end
function MSUF_GetCastbarDesiredSize(l,e,d,s,f)local i=i(l)local n=u[i]e=e or c()local t=n and a(e[n.w])or nil local o=n and a(e[n.h])or nil local r=r(e,i)if r then local e=I(l,r,d)if e and e>0 then t=e end end if(not t or t<=0)and i~="player"and not(e and n and e[n.detached]==true)then local e=h(T(l),d)if e and e>0 then t=e end end if not t or t<=0 then t=a(e.castbarGlobalWidth)or s or 250 end if not o or o<=0 then o=a(e.castbarGlobalHeight)or f or 18 end return t,o end
local function E(e)if e then C[i(e)]=nil else for t,e in ipairs(P)do C[e]=nil end end end
local function h(e)if not e then return"nil"end local n=(e.GetWidth and e:GetWidth())or 0 local a=(e.GetHeight and e:GetHeight())or 0 local t=(e.GetEffectiveScale and e:GetEffectiveScale())or 1 local e=(e.IsShown and e:IsShown())and 1 or 0 return b(l(n*100))..":"..b(l(a*100))..":"..b(l(t*1000))..":"..e end
local function b(a,t)t=i(t)if not M(t,a)then return nil end local a=r(a,t)if not a then return nil end if a=="unitframe"then local e=a local a=t=="boss"and 5 or 1 for a=1,a do local t=t=="boss"and("boss"..a)or t;e=e.."|"..t.."="..h(f(t)).."/"..h(T(t))end return e end local n,t=B(a)local e,n,t=e[n],m(t),t and e[t]or nil return a.."|a="..h(e).."|b="..h(n).."|g="..h(t)end
local function I(t,e)e=i(e)local t=b(t,e)if not t then C[e]=nil return false end if C[e]==t then return false end C[e]=t return true end
local function h()if d()then o=true;_=false;return end if _ then return end _=true;local t=function()_=false;if d()then o=true;return end local t=c()for a,e in ipairs(P)do if I(t,e)then g(e,t)end end end;local a=e.MSUF_Castbars_RunNextFrame if n(a)=="function"then a(t)elseif e.C_Timer and e.C_Timer.After then e.C_Timer.After(0,t)else t()end end
local function b(e)if not(e and e.HookScript)or G[e]then return false end G[e]=true;e:HookScript("OnSizeChanged",h);e:HookScript("OnShow",h);e:HookScript("OnHide",h)return true end
local function C(a,t)local a=r(a,t)if not a then return false end if a=="unitframe"then local e=false local a=i(t)=="boss"and 5 or 1 for a=1,a do local t=i(t)=="boss"and("boss"..a)or t;e=b(f(t))or e;e=b(T(t))or e end return e end local t,a=B(a)local t=b(e[t])local n=m(a)t=b(n)or t;if a and e[a]~=n then t=b(e[a])or t end return t end
local function t()if d()then o=true;S=false;return end y=y+1;local a=c()local n=false local o=false for t,e in ipairs(P)do if r(a,e)then o=true;if not C(a,e)then n=true end end end if not o then S=false;return end if not n then S=false;h();return end local a=A[y]if a and e.C_Timer and e.C_Timer.After then e.C_Timer.After(a,t)else S=false end end
local function b()if S or not(e.C_Timer and e.C_Timer.After)then return end if d()then o=true;return end S=true;y=0;e.C_Timer.After(0,t)end
function MSUF_UpdateCastbarWidthSourceSync(e,t,a)local n=not t;e=e or c()if d()then o=true;return end if not a then E(t)end if t then if not r(e,t)then return end;if not C(e,t)then b()end;if I(e,t)then g(t,e)end;return end local t=false for n,a in ipairs(P)do if r(e,a)then t=true;if not C(e,a)then b()end end end if t then h()end end
local t=CreateFrame("Frame")t:RegisterEvent("PLAYER_ENTERING_WORLD");t:RegisterEvent("PLAYER_REGEN_ENABLED");t:SetScript("OnEvent",function(t,e)if e=="PLAYER_REGEN_ENABLED"then if not o and not _ then return end elseif d()then o=true;return end o=false;local e=c();MSUF_UpdateCastbarWidthSourceSync(e,nil,true);h()end)function MSUF_ApplyPlayerCastbarIconLayout(t,r,i,d)if not(t and r and t.statusBar)then return end local n=t.statusBar i=a(i)or 0;d=a(d)or 0;local f=(t.GetHeight and t:GetHeight())or 18 local o=r.castbarShowIcon~=false;if r.castbarPlayerShowIcon~=nil then o=r.castbarPlayerShowIcon~=false end local l=t==e.MSUF_PlayerCastbar or t==e.MSUF_PlayerCastbarPreview or t==e.PlayerCastingBarFrame or t==e.CastingBarFrame;if l and(e.MSUF_UnitEditModeActive==true or(EditModeManagerFrame and EditModeManagerFrame.IsShown and EditModeManagerFrame:IsShown()))then o=true end local l=a(r.castbarPlayerIconOffsetX);if l==nil then l=a(r.castbarIconOffsetX)or 0 end local s=a(r.castbarPlayerIconOffsetY);if s==nil then s=a(r.castbarIconOffsetY)or 0 end local r=a(r.castbarPlayerIconSize)or a(r.castbarIconSize)or f;if r<6 then r=6 elseif r>128 then r=128 end local e=t.Icon or t.icon or(t.IconFrame and t.IconFrame.Icon)local c=l~=0;if e then if o then e:Show();local a=t._msufPCIconHost;if not a then a=CreateFrame("Frame",nil,t);a:EnableMouse(false);t._msufPCIconHost=a end;a:SetSize(r,r);a:ClearAllPoints();a:SetPoint("LEFT",t,"LEFT",l,s);if n.GetFrameLevel and a.SetFrameLevel then a:SetFrameLevel((n:GetFrameLevel()or 0)+3)end;a:Show();local t="H:"..(c and"D"or"A")..":"..r..":"..l..":"..s;if e._msufPCIconKey~=t or(e.GetParent and e:GetParent()~=a)then e:SetParent(a);e:ClearAllPoints();e:SetAllPoints(a);if e.SetDrawLayer then e:SetDrawLayer("OVERLAY",7)end;e._msufPCIconKey=t end else e:Hide();if t._msufPCIconHost then t._msufPCIconHost:Hide()end end elseif t._msufPCIconHost then t._msufPCIconHost:Hide()end local a=(o and e and not c)and("G:"..r)or"F"if n._msufPCLayoutKey~=a then n:ClearAllPoints();if o and e and not c then n:SetPoint("TOPLEFT",t,"TOPLEFT",r+1,i);n:SetPoint("BOTTOMRIGHT",t,"BOTTOMRIGHT",0,d)else n:SetPoint("TOPLEFT",t,"TOPLEFT",0,i);n:SetPoint("BOTTOMRIGHT",t,"BOTTOMRIGHT",0,d)end;n._msufPCLayoutKey=a end local a=(t.GetWidth and t:GetWidth())or 250;if a<=0 then a=250 end;local e=(o and e and not c)and(a-r-1)or a;if e<1 then e=1 end;local a=f-2;if a<1 then a=1 end;if n._msufPCSbW~=e then n:SetWidth(e);n._msufPCSbW=e end;if n._msufPCSbH~=a then n:SetHeight(a);n._msufPCSbH=a end;if t.backgroundBar and t.backgroundBar.SetAllPoints then t.backgroundBar:ClearAllPoints();t.backgroundBar:SetAllPoints(n)end end
local function h(t,r,o,a)if not t then return end local l=e.MSUF_Snap;if n(l)=="function"then if o~=nil then o=l(t,o)end;if a~=nil then a=l(t,a)end end;F(t,o);H(t,a);if t.statusBar then e.MSUF_ApplyPlayerCastbarIconLayout(t,r,-1,1)end;if t.empowerStageTicks then local a=t:GetHeight()or a;for t,e in pairs(t.empowerStageTicks)do if e and e.SetHeight then e:SetHeight(a)end end end;if t.statusBar then local n=r and r.castbarShowSpark==true local e=t.spark;if n and not e then e=t.statusBar:CreateTexture(nil,"OVERLAY",nil,6);e:SetTexture(4417031);e:SetTexCoord(0.222168,0.232422,0.294434,0.317383);e:SetDesaturated(true);e:SetVertexColor(1,1,1,1);e:SetBlendMode("ADD");t.spark=e end;if e then if e.SetShown then e:SetShown(n)elseif n then e:Show()else e:Hide()end;if n then local a=(r and r.castbarSparkOverflow~=false)and math.max(4,(t:GetHeight()or a or 18)*2.1)or(t:GetHeight()or a or 18);e:SetSize(16,a);local t=t.statusBar:GetStatusBarTexture();if t then e:ClearAllPoints();e:SetPoint("CENTER",t,"RIGHT",0,0)end end end end end
g=function(t,r)if d()then o=true;return false end r=r or c();t=i(t)if not M(t,r)then return false end local function i(t,a,e)if not t then return false end;F(t,a);if e and e>0 then H(t,e)end;return true end;if t=="player"then local t=e.MSUF_PlayerCastbar local e=e.MSUF_PlayerCastbarPreview local a=t or e;if not a then return false end;local n,a=MSUF_GetCastbarDesiredSize("player",r,a,250,18);if t then h(t,r,n,a)end;if e then h(e,r,n,a)end;return true elseif t=="target"or t=="focus"then local a=(t=="target"and(e.MSUF_TargetCastbar or e.TargetCastBar))or(e.MSUF_FocusCastbar or e.FocusCastBar)local l=(t=="target"and e.MSUF_TargetCastbarPreview)or e.MSUF_FocusCastbarPreview local o=a or l;if not o then return false end;local t,o=MSUF_GetCastbarDesiredSize(t,r,o,(o.GetWidth and o:GetWidth())or 240,(o.GetHeight and o:GetHeight())or 18);if a and i(a,t,o)and a.statusBar then local e=(a.GetHeight and a:GetHeight())or o or 18;F(a.statusBar,math.max(1,(t or 240)-e-1))end;if l and n(e.MSUF_ApplyPlayerCastbarSizeAndLayout)=="function"then e.MSUF_ApplyPlayerCastbarSizeAndLayout(l,r,t,o)end;return true elseif t=="boss"then local o=false local t=a(e.MSUF_MAX_BOSS_FRAMES or e.MAX_BOSS_FRAMES)or 5;if t<1 or t>12 then t=5 end;for t=1,t do local e=(e.MSUF_BossCastbars and e.MSUF_BossCastbars[t])or e["MSUF_BossCastbar"..t]if e then local t,a=MSUF_GetCastbarDesiredSize("boss"..t,r,e,(e.GetWidth and e:GetWidth())or 240,(e.GetHeight and e:GetHeight())or 12);if i(e,t,a)then o=true;if e.ApplyLayout then e:ApplyLayout()end end end end;if e.MSUF_UnitEditModeActive==true and n(e.MSUF_UpdateBossCastbarPreview)=="function"then e.MSUF_UpdateBossCastbarPreview();o=true end;return o end return false end
local function c(t,a)if t then t:SetScript("OnUpdate",nil);if t.timeText and e.MSUF_IsCastTimeEnabled(t)then e.MSUF_SetTextIfChanged(t.timeText,"")end;if t.latencyBar then t.latencyBar:Hide()end;t:Hide()end;if a then a:Hide()end end
local function S(o)EnsureDB();local r=e.MSUF_DB and e.MSUF_DB.general or{}local t=(o=="target"and(e.MSUF_TargetCastbar or e.TargetCastBar))or(e.MSUF_FocusCastbar or e.FocusCastBar)local d=(o=="target"and e.MSUF_TargetCastbarPreview)or e.MSUF_FocusCastbarPreview;if not t then return end;if not M(o,r)then c(t,d);return end local i=u[o]local c=f(o)local f=l((a(r[i.x])or(o=="focus"and a(r.castbarTargetOffsetX))or i.dx)+0.5)local a=l((a(r[i.y])or(o=="focus"and a(r.castbarTargetOffsetY))or i.dy)+0.5)if r[i.detached]then s(t,"CENTER",UIParent,"CENTER",f,a)else if not c then return end;s(t,"BOTTOMLEFT",c,"TOPLEFT",f,a)end;MSUF_UpdateCastbarWidthSourceSync(r,o,true);local a,i=MSUF_GetCastbarDesiredSize(o,r,t,(t.GetWidth and t:GetWidth())or 240,(t.GetHeight and t:GetHeight())or 18);local l=e.MSUF_Snap;if n(l)=="function"then a=l(t,a)end;local l=(t.GetHeight and t:GetHeight())or i or 18;F(t,a);if t.statusBar then F(t.statusBar,math.max(1,a-l-1))end;if d and n(e.MSUF_ApplyPlayerCastbarSizeAndLayout)=="function"then e.MSUF_ApplyPlayerCastbarSizeAndLayout(d,r,a,i)end;local a=(n(e.MSUF_IsCastTimeEnabled)=="function")and e.MSUF_IsCastTimeEnabled(t)or true;if t.timeText and t.statusBar then t.timeText:Show();p(t.timeText,a and 1 or 0);if not a then e.MSUF_SetTextIfChanged(t.timeText,"")end;local n=r[o=="target"and"castbarTargetTimeOffsetX"or"castbarFocusTimeOffsetX"];if n==nil then n=r.castbarPlayerTimeOffsetX or-2 end;local a=r[o=="target"and"castbarTargetTimeOffsetY"or"castbarFocusTimeOffsetY"];if a==nil then a=r.castbarPlayerTimeOffsetY or 0 end;s(t.timeText,"RIGHT",t.statusBar,"RIGHT",n,a);if e.MSUF_SetJustifyHIfChanged then e.MSUF_SetJustifyHIfChanged(t.timeText,"RIGHT")else t.timeText:SetJustifyH("RIGHT")end end;if n(e.MSUF_ApplyCastbarTimeTextLayout)=="function"then e.MSUF_ApplyCastbarTimeTextLayout(t,o)end;local e=o=="target"and e.MSUF_PositionTargetCastbarPreview or e.MSUF_PositionFocusCastbarPreview;if d and e then e()end end
function MSUF_ReanchorTargetCastBar()S("target")end
function MSUF_ReanchorFocusCastBar()S("focus")end
function MSUF_ReanchorPlayerCastBar()EnsureDB();local t=e.MSUF_DB and e.MSUF_DB.general or{}if not(e.MSUF_ShouldUseBlizzardCastbar and e.MSUF_ShouldUseBlizzardCastbar("player",t))and e.MSUF_HideBlizzardPlayerCastbar then e.MSUF_HideBlizzardPlayerCastbar()end;if not M("player",t)then local t=e.MSUF_PlayerCastbar_ApplyBackendState;if n(t)=="function"then t()end;c(e.MSUF_PlayerCastbar,e.MSUF_PlayerCastbarPreview);return end;local a=e.MSUF_PlayerCastbar_ApplyBackendState;if n(a)=="function"then a()else MSUF_InitSafePlayerCastbar()end local a=f("player")if not e.MSUF_PlayerCastbar or(not t.castbarPlayerDetached and not a)then return end local r=l((t.castbarPlayerOffsetX or 0)+0.5)local o=l((t.castbarPlayerOffsetY or 5)+0.5)if t.castbarPlayerDetached then s(e.MSUF_PlayerCastbar,"CENTER",UIParent,"CENTER",r,o)else s(e.MSUF_PlayerCastbar,"BOTTOM",a,"TOP",r,o)end;MSUF_UpdateCastbarWidthSourceSync(t,"player",true);local a,r=MSUF_GetCastbarDesiredSize("player",t,e.MSUF_PlayerCastbar,250,18);h(e.MSUF_PlayerCastbar,t,a,r);if e.MSUF_PlayerCastbar.timeText and e.MSUF_PlayerCastbar.statusBar then local n=t.castbarPlayerTimeOffsetX or-2 local a=t.castbarPlayerTimeOffsetY or 0;s(e.MSUF_PlayerCastbar.timeText,"RIGHT",e.MSUF_PlayerCastbar.statusBar,"RIGHT",n,a);if e.MSUF_SetJustifyHIfChanged then e.MSUF_SetJustifyHIfChanged(e.MSUF_PlayerCastbar.timeText,"RIGHT")else e.MSUF_PlayerCastbar.timeText:SetJustifyH("RIGHT")end;local t=t.showPlayerCastTime~=false;e.MSUF_PlayerCastbar.timeText:Show();p(e.MSUF_PlayerCastbar.timeText,t and 1 or 0);if not t then e.MSUF_PlayerCastbar.timeText:SetText("")end end;if n(e.MSUF_ApplyCastbarTimeTextLayout)=="function"then e.MSUF_ApplyCastbarTimeTextLayout(e.MSUF_PlayerCastbar,"player")end;if e.MSUF_PlayerCastbarPreview then h(e.MSUF_PlayerCastbarPreview,t,a,r)end;if e.MSUF_PlayerCastbarPreview and e.MSUF_PositionPlayerCastbarPreview then e.MSUF_PositionPlayerCastbarPreview()end end
MSUF_PlayerCastbarManageHooked=true
function MSUF_ReanchorBossCastBar()if n(e.MSUF_ApplyBossCastbarPositionSetting)=="function"then e.MSUF_ApplyBossCastbarPositionSetting(false)end;if not d()and n(e.MSUF_UpdateBossCastbarPreview)=="function"then e.MSUF_UpdateBossCastbarPreview()end;if n(MSUF_SyncBossCastbarSliders)=="function"then MSUF_SyncBossCastbarSliders()end;if n(MSUF_SyncCastbarPositionPopup)=="function"then MSUF_SyncCastbarPositionPopup("boss")end end
e.MSUF_ReanchorTargetCastBar=MSUF_ReanchorTargetCastBar
e.MSUF_ReanchorFocusCastBar=MSUF_ReanchorFocusCastBar
e.MSUF_NormalizeCastbarWidthSource=U
e.MSUF_NormalizePlayerCastbarWidthSource=U
e.MSUF_GetCastbarWidthSourceKey=function(t)local t=u[i(t)]return t and t.match end
e.MSUF_GetCastbarDesiredSize=MSUF_GetCastbarDesiredSize
e.MSUF_UpdateCastbarWidthSourceSync=MSUF_UpdateCastbarWidthSourceSync
e.MSUF_ApplyCastbarEffectiveSizeUnit=g
e.MSUF_GetPlayerCastbarDesiredSize=function(a,t,r,n)return MSUF_GetCastbarDesiredSize("player",a,t,r,n)end
e.MSUF_ApplyPlayerCastbarSizeAndLayout=h
e.MSUF_ApplyPlayerCastbarIconLayout=MSUF_ApplyPlayerCastbarIconLayout
e.MSUF_ReanchorPlayerCastBar=MSUF_ReanchorPlayerCastBar
e.MSUF_ReanchorBossCastBar=MSUF_ReanchorBossCastBar
