local addonName, MSUF = ...
MSUF = MSUF or {}

local M = MSUF.MSUF2 or {}
MSUF.MSUF2 = M

local Data = M.SearchData or {}
M.SearchData = Data

if type(Data.RegisterFAQProvider) == "function" then
    Data.RegisterFAQProvider(function(env)
        local SearchKeywordList, SEARCH_DISPEL_DEBUFF_KEYWORDS, SEARCH_HIGHLIGHT_BORDER_KEYWORDS, SEARCH_DISPEL_OVERLAY_KEYWORDS, SEARCH_DEBUFF_STRIPE_KEYWORDS, SEARCH_BLIZZARD_DISPEL_KEYWORDS, SEARCH_UNIT_AURA_DISPEL_KEYWORDS = Data.FAQEnv(env, [[SearchKeywordList SEARCH_DISPEL_DEBUFF_KEYWORDS SEARCH_HIGHLIGHT_BORDER_KEYWORDS SEARCH_DISPEL_OVERLAY_KEYWORDS SEARCH_DEBUFF_STRIPE_KEYWORDS SEARCH_BLIZZARD_DISPEL_KEYWORDS SEARCH_UNIT_AURA_DISPEL_KEYWORDS]])

        return Data.FAQRows({
            { l = "Where is the unit frame range check?", a = "Open the matching unit page > Range Fade. Group range fade is still in Group Frames > Health & Text.", p = "uf_target", t = "Opens: Target > Range Fade", x = "Range Fade unit frame range check range checker distance check out of range alpha target targettarget focus focustarget pet boss", k = "unit frame range check|unitframe range check|unit frames range check|range check unitframe|range check unit frame|range checker|distance check|distance checker|out of range unit frame|out of range frames|target out of range|focus out of range|boss out of range|target range fade|focus range fade|boss range fade|reichweitencheck|reichweite check|entfernung check", y = 165 },
        },
        [[
How do I change language or translations?	Open Global Style > Miscellaneous > Language. Translation coverage can also be checked with the /msuf locale command.	opt_misc	Opens: Global Style > Miscellaneous > Language	Language locale localization translation deDE ruRU frFR esES	language|locale|translation|translations|localization|localisation|sprache|deutsch|english|russian|french|spanish	25
How do I change unitframe or group frame tooltips?	Open Global Style > Miscellaneous > Unitframe tooltips to control tooltip source, anchor, visibility mode, and modifier key for MSUF unit and group frames.	opt_misc	Opens: Global Style > Miscellaneous > Unitframe tooltips	Unitframe tooltips group frame tooltips tooltip mouseover modifier hide tooltip show tooltip	tooltip|tooltips|unit tooltip|group tooltip|group frame tooltip|mouseover tooltip|hide tooltip|show tooltip|tooltip on mouseover|modifier tooltip	20
How do I change click, mouseover, or targeting behavior?	Open Gameplay for crosshair, click-cast, focus/target modifier, mouseover, interaction, and targeting options.	gameplay	Opens: Gameplay	Gameplay click cast focus target modifier mouseover interaction targeting combat crosshair	click cast|clickcast|click casting|clickthrough|click-through|mouseover|target modifier|focus modifier|mouse buttons|targeting|combat crosshair	30
How do I change class resources?	Open Class Resources for combo points, holy power, soul shards, chi, maelstrom, essence, runes, stagger, detached power, and alternative mana.	classpower	Opens: Class Resources	Class Resources Layout Behavior Style Auto-Hide Detached Power Bar Alternative Mana	class resource|class resources|combo points|holy power|soul shards|chi|maelstrom|essence|runes|stagger|alternative mana|alt mana|detached power	25
How do I hide or show a unit frame?	Open that unit page and use Frame Basics > Enable. Boss frames also have Boss Layout options.	uf_player	Opens: Player > Frame Basics	Frame Basics Enable hide show player target focus boss pet	hide unitframe|show unitframe|disable unitframe|enable unitframe|hide player frame|hide target frame|hide focus frame|hide pet frame|show player frame|enable target frame|disable boss frame	30
Where are load conditions?	Open the matching unit page and use Load Conditions to control when player, target, focus, boss, or pet frames are shown.	uf_player	Opens: Player > Load Conditions	Load Conditions show hide visibility player target focus boss pet combat group instance	load conditions|visibility conditions|show conditions|hide conditions|when to show frame|when to hide frame|frame visibility|combat visibility|instance visibility|ladebedingungen|sichtbarkeit	80
Why is my player, target, focus, or pet frame gone?	Open the matching unit page and check Frame Basics > Enable, Load Conditions, alpha/transparency, and range fade.	uf_player	Opens: Player > Frame Basics	Frame Basics Enable Load Conditions Transparency Range Fade player target focus pet gone missing invisible	player frame gone|target frame gone|focus frame gone|pet frame gone|unitframe missing|unitframe invisible|frame not visible|frame disappeared|cannot see player frame|target not showing|focus not showing|pet not showing|unitframe hidden	55
Where is Target of Target?	Open Target of Target. Use Frame Basics to enable it, Text for labels, and Anchoring/Edit Mode for placement.	uf_targettarget	Opens: Target of Target > Frame Basics	Frame Basics Target of Target ToT Enable Text Anchoring	target of target|tot|targettarget|target target|where is tot|tot missing|show target of target|enable tot|target of target frame	45
Where is Focus Target?	Open Focus Target. Use Frame Basics to enable it; it only appears when Focus is enabled and your focus has a target.	uf_focustarget	Opens: Focus Target > Frame Basics	Frame Basics Focus Target Enable Text Anchoring	focus target|focustarget|focus target frame|ft frame|where is focus target|focus target missing|show focus target|enable focus target	45
Why is my castbar not showing?	Open the unit page > Castbar to enable that unit's castbar. Shared castbar visuals are in Global Style > Castbar.	uf_player	Opens: Player > Castbar	Castbar Enable player target focus boss pet show interrupt icon text	castbar not showing|castbar missing|player castbar gone|target castbar missing|focus castbar missing|boss castbar missing|show castbar|enable castbar|my castbar disappeared|no cast bar	55
Where do I change castbar spell names or long cast text?	Open Global Style > Castbar > Name Shortening for castbar spell name shortening, max length, and reserved space.	opt_castbar	Opens: Global Style > Castbar > Name Shortening	Name Shortening spell name max name length reserved space castbar	cast name too long|spell name too long|castbar text too long|shorten castbar name|castbar spell name|max name length|reserved space|cast text overlap	45
Why are class resources missing?	Open Class Resources. Check Enable, Auto-Hide, class-specific behavior, detached power, and alternative mana settings.	classpower	Opens: Class Resources > Layout / Auto-Hide	Class Resources Enable Auto-Hide Behavior Detached Power Bar Alternative Mana	class resources missing|combo points missing|holy power missing|soul shards missing|chi missing|maelstrom missing|essence missing|runes missing|stagger missing|class power not showing|resource bar missing	55
Where do I configure detached power or alternative mana?	Open Class Resources for global class-resource bars. Per-unit detached power options are in the unit page > Power Bar.	classpower	Opens: Class Resources > Detached Power Bar	Detached Power Bar Alternative Mana Power Bar class resources sync width anchor	detached power|detached power bar|alternative mana|alt mana|dual resource|power bar detached|anchor to class resource|sync width to class resource	45
        ]],
        {
            { "Why are my buffs or debuffs missing?", "Open Auras > Filters. Check the active scope, Only Mine, boss/raid filters, dispellable filters, and blacklist entries.", "auras3_filters", "Opens: Auras > Filters", "Aura Filters Blacklist Only my buffs Only my debuffs Show Debuffs Include boss buffs dispellable", SearchKeywordList(SEARCH_UNIT_AURA_DISPEL_KEYWORDS, SEARCH_DISPEL_DEBUFF_KEYWORDS, SEARCH_BLIZZARD_DISPEL_KEYWORDS, "buffs missing|debuffs missing|auras missing|buff not showing|debuff not showing|hide buffs|show debuffs|only my buffs|only my debuffs|boss aura missing|dispellable debuff missing|aura filter"), 180, },
        },
        [[
Why do I have too many buffs or debuffs?	Open the relevant Unit Frame or Group Frames > Auras page to adjust icon size, rows, caps and spacing. Use Auras > Filters for filtering.	gf_auras	Opens: Group Frames > Auras	Auras Max Buffs Max Debuffs Icon size rows spacing filters style	too many buffs|too many debuffs|too many auras|aura spam|buff spam|debuff spam|max buffs|max debuffs|aura cap|icon size|aura rows	55
How do I turn off player buffs only?	Open Player > Auras, then turn off Buffs for the player frame. Use Auras > Style for text and cooldown styling.	uf_player	Opens: Player > Auras	Player Auras Buffs Debuffs hide player buffs only	how do i turn off player buffs only its greyed out when editing player auras|how do i turn off player buffs only|player buffs greyed out|player buffs grayed out|show buffs greyed out player auras|show buffs grayed out player auras|turn off buffs only player|disable player buffs only|hide player buffs only|remove player buffs only|player aura buffs disabled|player auras show buffs locked|custom caps max buffs 0 player|max buffs 0 player|buffs nur beim spieler ausblenden|spieler buffs ausblenden|spieler buffs deaktivieren|spieler buffs ausgegraut|spieler auren buffs ausgegraut|show buffs spieler ausgegraut|max buffs 0 spieler|desactivar buffs jugador|ocultar buffs jugador|buffs jugador gris|auras jugador buffs gris|desactiver buffs joueur|masquer buffs joueur|buffs joueur grise|auras joueur buffs grise|disattivare buff giocatore|nascondere buff giocatore|buff giocatore grigio|desativar buffs jogador|ocultar buffs jogador|buffs jogador cinza|ÐºÐ°Ðº Ð¾Ñ‚ÐºÐ»ÑŽÑ‡Ð¸Ñ‚ÑŒ Ð±Ð°Ñ„Ñ„Ñ‹ Ð¸Ð³Ñ€Ð¾ÐºÐ°|Ð±Ð°Ñ„Ñ„Ñ‹ Ð¸Ð³Ñ€Ð¾ÐºÐ° ÑÐµÑ€Ñ‹Ðµ|Ð°ÑƒÑ€Ñ‹ Ð¸Ð³Ñ€Ð¾ÐºÐ° Ð±Ð°Ñ„Ñ„Ñ‹ ÑÐµÑ€Ñ‹Ðµ|í”Œë ˆì´ì–´ ë²„í”„ ë„ê¸°|í”Œë ˆì´ì–´ ë²„í”„ ë¹„í™œì„±í™”|í”Œë ˆì´ì–´ ì˜¤ë¼ ë²„í”„ íšŒìƒ‰|å…³é—­çŽ©å®¶å¢žç›Š|çŽ©å®¶å¢žç›Šç°è‰²|çŽ©å®¶å…‰çŽ¯å¢žç›Šç°è‰²|é—œé–‰çŽ©å®¶å¢žç›Š|çŽ©å®¶å¢žç›Šç°è‰²|çŽ©å®¶å…‰ç’°å¢žç›Šç°è‰²	720
Where do I change aura cooldown text?	Open Auras > Style for timer colors, stack text, cooldown text size, and group-frame aura text styling.	auras3_styling	Opens: Auras > Style	Style Cooldown Timer Text cooldown text size safe warning urgent stack count	aura cooldown text|aura cooldown text too small|aura timer too small|buff timer|debuff timer|cooldown text size|stack text size|timer color|aura timer color|cooldown swipe|pandemic color	150
        ]],
        {
            { "Where do I change group health text or power bars?", "Open Group Frames > Health & Text. It controls health colors, bars, power bar, text, dispel overlay, debuff stripe, and range fade. Heal prediction is in Global Style > Bars > Absorb Display.", "gf_bars", "Opens: Group Frames > Health & Text", "Health Colors Bars Power Bar Text Dispel Overlay Debuff Stripe Range Fade group range check raid range check party range check", SearchKeywordList(SEARCH_DISPEL_OVERLAY_KEYWORDS, SEARCH_DEBUFF_STRIPE_KEYWORDS, "group health text|raid health text|party health text|group power bar|raid power bar|party power bar|heal prediction|incoming heals|dispel overlay|debuff stripe|group range fade|group range check|raid range check|party range check|raid out of range|party out of range|range check raid frames"), 180, },
        },
        [[
Where is party or raid range check?	Open Group Frames > Health & Text > Range Fade. Affects chooses frame or HP fading, and the alpha sliders control out-of-range and offline opacity.	gf_bars	Opens: Group Frames > Health & Text > Range Fade	Range Fade group frame range check raid range check party range check out of range alpha offline opacity affects frame HP	group range check|group frame range check|group frames range check|raid range check|raid frame range check|raid frames range check|party range check|party frame range check|party frames range check|raid out of range|party out of range|group out of range|range check raid frames|range check party frames	140
Where are absorb bars or heal prediction?	Absorb styling and heal prediction are in Global Style > Bars > Absorb Display. Use the Party or Raid scope there for group incoming heals.	opt_bars	Opens: Global Style > Bars > Absorb Display	Absorb Display Heal Prediction incoming heals absorb health group frames	absorb|absorbs|absorb bar|absorb texture|heal prediction|incoming heals|healing prediction|shields|shield bar|health absorb	45
        ]],
        {
            { "Where do I change aggro, threat, dispel, or raid markers?", "Use Global Style > Bars for highlight borders and Group Frames > Indicators for role, threat, dispel, spell, corner, and raid-marker indicators.", "gf_indicators", "Opens: Group Frames > Indicators", "Indicators Status Icons Spell Indicators Corner Indicators aggro threat dispel role icon raid marker", SearchKeywordList(SEARCH_HIGHLIGHT_BORDER_KEYWORDS, SEARCH_DISPEL_DEBUFF_KEYWORDS, "aggro|threat|aggro border|threat border|dispel indicator|magic indicator|curse indicator|poison indicator|disease indicator|raid marker|role icon|ready check|leader icon"), 220, },
        },
        [[
Why is text overlapping or in the wrong place?	Open the unit page > Text. Adjust anchors, offsets, font size, spacing, split spacing, and layer/draw order.	uf_player	Opens: Player > Text	Text anchor offset font size layer draw order spacing split spacing overlaps bars portraits status icons	text overlap|text overlapping|text wrong place|text on bar|text on portrait|name overlap|hp text overlap|power text overlap|draw order|text layer|split spacing|move text	55
Why is MSUF lagging or costing FPS?	Reduce expensive aura layouts first: lower visible aura counts, timer text, and filter work in Auras > Style and Auras > Filters.	auras3_styling	Opens: Auras > Style	Auras performance lag fps cooldown timers filters aura count style	lag|fps|performance|stutter|slow|too much cpu|heavy|optimize|aura performance|cooldown text performance|combat performance	55
        ]])
    end)
end
