local addonName, MSUF = ...
MSUF = MSUF or {}

local M = MSUF.MSUF2 or {}
MSUF.MSUF2 = M
_G.MSUF2 = M

local Data = M.SearchData or {}
M.SearchData = Data

if type(Data.RegisterFAQProvider) == "function" then
    Data.RegisterFAQProvider(function(env)
        local SearchKeywordList, SEARCH_DISPEL_DEBUFF_KEYWORDS, SEARCH_UNIT_AURA_DISPEL_KEYWORDS = Data.FAQEnv(env, [[SearchKeywordList SEARCH_DISPEL_DEBUFF_KEYWORDS SEARCH_UNIT_AURA_DISPEL_KEYWORDS]])

        return Data.FAQRows({
            { l = "Why can I not change something in combat?", a = "WoW blocks some protected frame changes in combat. Leave combat, then apply layout, anchoring, enable/disable, profile, or protected-frame changes.", p = "opt_misc", t = "Opens: Global Style > Miscellaneous", x = "combat lockdown protected frames settings in combat out of combat", k = "combat lockdown|cannot change in combat|can't change in combat|protected frame|blocked in combat|in combat settings|combat error|leave combat|why can't i move in combat", y = 50 },
        },
        [[
Where did the menu window go?	Open MSUF again with /msuf. If frame positions are broken, use Dashboard > Reset Positions or the profile/reset tools.	home	Opens: Dashboard > Reset Positions	Reset Positions menu window offscreen dashboard slash msuf recovery	menu gone|menu missing|window offscreen|menu offscreen|can't open menu|cannot open menu|lost menu|options window gone|reset menu position|where is menu	45
Why did my profile or import look wrong?	Open Profiles. Check active profile, spec profiles, import/export, and legacy imports. Large imports may need a reload.	profiles	Opens: Profiles > Profile Management / Export / Import	Profile Management Spec Profiles Export Import legacy imports active profile reload	profile wrong|profile missing|profile gone|import failed|import looks wrong|wago import wrong|profile not loading|spec profile wrong|active profile|legacy import|copy profile	55
Why are party or raid frames not showing?	Open Group Frames > Layout. Check enable/show behavior, player/solo visibility, layout mode, frame scaling, and anchoring.	gf_layout	Opens: Group Frames > Layout > General	General Layout show hide player solo party raid enable frame scaling anchoring	party frames not showing|raid frames not showing|group frames missing|party frames gone|raid frames gone|hide player solo|show party frames|show raid frames|group frames invisible|party hidden|raid hidden	60
Where do I make names shorter?	Open Global Style > Fonts > Name Shortening for unit names. Castbar spell name shortening is in Global Style > Castbar > Name Shortening.	opt_fonts	Opens: Global Style > Fonts > Name Shortening	Name Shortening names too long max name length castbar spell name shortening	name too long|names too long|shorten names|name shortening|long names|cut names|truncate names|player name too long|target name too long	45
Why are group names still shortened when name shortening is off?	Global Style > Fonts has Shared settings plus per-scope font overrides. If Party or Raid uses custom font settings, its Name Shortening can stay enabled even when Shared is off. Select Party/Raid in Fonts or reset the font override.	opt_fonts	Opens: Global Style > Fonts > Name Shortening / scope override	Name Shortening Use custom settings for this scope Overrides Party Raid group frame name truncation font override shared changes	see image not sure whats happening here|name shortening off but group names still shortened|shorten names disabled but names still cut|group names still shortened|party names still shortened|raid names still shortened|group frame name truncation override|group frame font override name shortening|shared name shortening does not affect party raid|getting confused with overrides|no group frame override|namen werden gekuerzt obwohl namenskuerzung aus|namenskuerzung aus aber gruppennamen gekuerzt|gruppenframe override namenskuerzung|raid override namenskuerzung|acortar nombres desactivado pero los nombres siguen acortados|abreviar nombres desactivado pero nombres cortados|marcos de grupo anulacion nombres|sobrescritura de marcos de grupo nombres|raccourcissement des noms desactive mais noms encore raccourcis|noms raccourcis malgre option desactivee|remplacement cadres de groupe noms|abbreviazione nomi disattivata ma nomi ancora abbreviati|nomi gruppo abbreviati override|encurtar nomes desativado mas nomes ainda encurtados|quadros de grupo substituicao nomes|ÑÐ¾ÐºÑ€Ð°Ñ‰ÐµÐ½Ð¸Ðµ Ð¸Ð¼ÐµÐ½ Ð¾Ñ‚ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¾ Ð½Ð¾ Ð¸Ð¼ÐµÐ½Ð° ÑÐ¾ÐºÑ€Ð°Ñ‰Ð°ÑŽÑ‚ÑÑ|ÑÐ¾ÐºÑ€Ð°Ñ‰ÐµÐ½Ð¸Ðµ Ð¸Ð¼Ñ‘Ð½ Ð²Ñ‹ÐºÐ»ÑŽÑ‡ÐµÐ½Ð¾ Ð½Ð¾ Ð¸Ð¼ÐµÐ½Ð° ÑÐ¾ÐºÑ€Ð°Ñ‰Ð°ÑŽÑ‚ÑÑ|Ð¾Ð²ÐµÑ€Ñ€Ð°Ð¹Ð´ Ñ€Ð°Ð¼Ð¾Ðº Ð³Ñ€ÑƒÐ¿Ð¿Ñ‹ ÑÐ¾ÐºÑ€Ð°Ñ‰ÐµÐ½Ð¸Ðµ Ð¸Ð¼ÐµÐ½|Ð¿ÐµÑ€ÐµÐ¾Ð¿Ñ€ÐµÐ´ÐµÐ»ÐµÐ½Ð¸Ðµ Ñ€Ð°Ð¼Ð¾Ðº Ð³Ñ€ÑƒÐ¿Ð¿Ñ‹ Ð¸Ð¼ÐµÐ½Ð°|ì´ë¦„ ì¤„ì´ê¸° êº¼ì§ì¸ë° ì´ë¦„ì´ ì¤„ì–´ë“¦|ì´ë¦„ ì¤„ì´ê¸° êº¼ì§ ì´ë¦„ ì¤„ì–´ë“¦|ê·¸ë£¹ í”„ë ˆìž„ ìž¬ì •ì˜ ì´ë¦„ ì¤„ì´ê¸°|åå­—ç¼©çŸ­å…³é—­ä½†ä»ç„¶ç¼©çŸ­|å§“åç¼©çŸ­å…³é—­ä½†ä»ç„¶ç¼©çŸ­|å›¢é˜Ÿæ¡†æž¶è¦†ç›–åå­—ç¼©çŸ­|å°é˜Ÿæ¡†æž¶è¦†ç›–åå­—ç¼©çŸ­|åå­—ç¸®çŸ­é—œé–‰ä½†ä»ç„¶ç¸®çŸ­|å§“åç¸®çŸ­é—œé–‰ä½†ä»ç„¶ç¸®çŸ­|åœ˜éšŠæ¡†æž¶è¦†è“‹åå­—ç¸®çŸ­|éšŠä¼æ¡†æž¶è¦†è“‹åå­—ç¸®çŸ­	650
Where do I make the menu bigger or smaller?	Use the Dashboard scale controls for menu scale or UI scale. You can also resize the MSUF2 window from its corner.	home	Opens: Dashboard > UI Scale / Menu Scale	UI Scale Menu Scale resize window bigger smaller dashboard	menu too big|menu too small|make menu bigger|make menu smaller|ui scale|menu scale|resize window|options too big|options too small	45
Where do I change click-through auras?	Open the unit page > Auras for click-through aura behavior. Gameplay contains click-cast and targeting behavior.	uf_player	Opens: Player > Auras	Auras click-through auras click through click cast gameplay targeting	clickthrough auras|click-through auras|click through auras|auras block mouse|can't click through buffs|aura mouse|click aura|click cast not working|mouse blocked by auras	45
Where are optional modules or style modules?	Open Modules > Style for optional style modules such as portrait decoration and dropdown styling.	modules	Opens: Modules > Style	Modules Style portrait decoration dropdown style optional modules skins	modules|optional modules|style modules|portrait decoration|portrait deco|module style|skins	70
How do I show party or raid frames while solo?	Open Group Frames > Layout and check the solo/player visibility options. That is where MSUF controls whether party-style frames appear when you are alone.	gf_layout	Opens: Group Frames > Layout > General	General show solo show player party raid group frames visibility	show party frames while solo|show raid frames while solo|solo raid frames|solo party frames|always show party frames|always show raid frames|show player solo|show self in party|party frames when alone|raid frames when alone	90
How do I hide myself from party or raid frames?	Open Group Frames > Layout. The General and Sorting sections control player/self visibility and how player units are ordered in group frames.	gf_layout	Opens: Group Frames > Layout > General	General Show player Player first in role Sorting party raid self visibility	hide myself from party|hide player in party|hide self in party frames|show player in party frames|player in raid frames|self in party frames|show player|player first in role|party contains me	75
How do I show only my HoTs or buffs on party frames?	Open Auras > Filters for group-frame aura filters, then use Group Frames > Auras for placement.	auras3_filters	Opens: Auras > Filters	Buffs own buffs only mine HoTs healer buffs group frames	show only my buffs party|only my hots|only my HoTs|track my hots|track my heals|show my rejuv|show my renew|show my shields|own buffs party|own buffs raid|healer hots|druid hots|priest hots	120
How do I make my own buffs or debuffs bigger?	Open Auras > Style for text and cooldowns. Icon size and placement live on the relevant unit page > Auras or Group Frames > Auras.	auras3_styling	Opens: Auras > Style	Auras icon size own buffs own debuffs custom buffs custom debuffs group buffs debuffs	make my buffs bigger|make own buffs bigger|make my debuffs bigger|bigger own buffs|bigger own debuffs|my buffs bigger|my debuffs bigger|own aura size|personal debuff size|personal buff size	95
How do I move buff or debuff icons near a unit frame?	Open the unit page > Auras or the aura Position Popup for unit-frame aura placement. Buff/debuff icons are configured as aura layout, not moved through MSUF Edit Mode.	uf_player	Opens: Player > Auras	Auras buffs debuffs position anchor rows spacing unit frame auras	move buffs|move debuffs|move buff icons|move debuff icons|buff icons next to unit frame|debuff icons next to unit frame|buffs under portrait|debuffs under portrait|unlock buffs debuffs|buff debuff anchor|anchor debuffs to buffs|buffs on top|debuffs on top	110
How do I add a specific boss debuff to the blacklist?	Open Auras > Filters for unit spell-ID blacklists and group category blacklists. Group aura placement stays in Group Frames > Auras.	auras3_filters	Opens: Auras > Filters	Filters Blacklist buffs debuffs boss debuffs spell id raid debuffs	boss debuff missing|boss debuffs not showing|raid debuff missing|add boss debuff|add spell id|spell id|spellid|debuff stack count|raid mechanic debuff	125
        ]],
        {
            { "How do I show only dispellable debuffs?", "Open Auras > Filters for unit-frame and group-frame Debuff filtering. Party/Raid status indicators stay in Group Frames > Indicators.", "auras3_filters", "Opens: Auras > Filters", "Filters Indicators dispel magic curse poison disease debuffs debuff type border group frames", SearchKeywordList(SEARCH_DISPEL_DEBUFF_KEYWORDS, SEARCH_UNIT_AURA_DISPEL_KEYWORDS, "only dispellable debuffs|dispellable debuffs|dispel debuffs|magic debuff|curse debuff|poison debuff|disease debuff|debuff type border|debuff color border|show dispels|healer dispels"), 260, },
        },
        [[
How do I move or resize target, focus, or boss castbars?	Use MSUF Edit Mode to drag supported castbars. Per-unit castbar enable/icon/text options are on each unit page; shared castbar style is in Global Style > Castbar.	home	Opens: Dashboard > MSUF Edit Mode	MSUF Edit Mode move castbars target castbar focus castbar boss castbar player castbar resize	move target castbar|move focus castbar|move boss castbar|move enemy castbar|resize target castbar|resize focus castbar|target cast bar position|focus cast bar position|boss cast bar position|castbar edit mode|drag castbar	115
How do I stop castbars covering party or raid frames?	MSUF group frames do not use per-player castbars over the health frame. For MSUF castbar positioning, use MSUF Edit Mode and Global Style > Castbar.	opt_castbar	Opens: Global Style > Castbar	Castbar position edit mode group frames party raid castbars over health	party castbar covering health|raid castbar over frame|castbar covers party frame|castbar covers raid frame|group castbar position|party frame castbar|raid frame castbar|cast bars on raid frames	70
Why can I not unlock or drag buffs and debuffs?	MSUF Edit Mode moves frames and supported castbars. Aura icon placement is controlled from each unit page > Auras or Group Frames > Auras.	uf_player	Opens: Player > Auras	Auras aura position buffs debuffs edit mode drag unlock frames	can't unlock buffs|can't unlock debuffs|cannot move buffs|cannot move debuffs|unlock buff frames|unlock debuff frames|drag buffs debuffs|buffs not movable|debuffs not movable|lock frames buffs|unlock frames buffs	130
How do I make raid frames cleaner for healing?	Use Group Frames > Layout for frame size and spacing, Auras for Buff/Debuff placement, and Indicators for fixed-position status icons.	gf_layout	Opens: Group Frames > Layout / Auras / Indicators	Layout Auras Buffs Debuffs Indicators healer clean raid frames HoTs fixed positions	clean raid frames|healer raid frames|minimal raid frames|declutter raid frames|fixed hots positions|fixed aura positions|healer hots indicators|raid frame indicators|too much information raid frames|healing frames setup	100
How do I change dead, offline, AFK, or ready-check indicators?	Open Group Frames > Indicators for status icons, role/leader/assist, ready check, focus glow, and other group-frame state indicators.	gf_indicators	Opens: Group Frames > Indicators > Status Icons	Status Icons ready check dead ghost offline afk dnd leader assist role icon	dead icon|offline icon|afk icon|dnd icon|ghost icon|ready check icon|leader icon|assist icon|status icons|group status icon|raid status icon	85
How do I hide realm names or shorten player names?	Open Global Style > Fonts > Name Shortening. It controls name shortening globally; unit text placement is on each unit page > Text.	opt_fonts	Opens: Global Style > Fonts > Name Shortening	Name Shortening realm names short names player names font text	hide realm names|remove realm names|short names|shorten player names|names too long|realm name showing|server name showing|name realm|truncate names	90
How do I get class-colored health bars or names?	Open Global Style > Colors for class bar colors and unitframe colors. Group health colors are in Group Frames > Health & Text.	opt_colors	Opens: Global Style > Colors > Class Bar Colors	Class Bar Colors Unitframe Colors Group Health Colors class colored names health bars	class colored health|class colored names|class color names|class color health bars|green health bars|health bar class color|target class color|player class color|raid class colors	105
How do I change click-casting so aura icons do not block heals?	Open the relevant unit page > Auras for click-through aura behavior, then use Gameplay for click-cast, mouseover, and targeting behavior.	uf_player	Opens: Player > Auras	Auras click-through auras Gameplay click cast mouseover healing party frames	auras block heals|buffs block click casting|debuffs block click cast|can't heal through buffs|mouseover heal blocked|click cast blocked by aura|heal mouseover auras|party frame click through buffs	115
How do I open the MSUF options?	Use /msuf to open MSUF2. The Dashboard also contains reset, support, profile, and scale tools.	home	Opens: Dashboard	Dashboard slash command msuf options menu support profiles reset	how to open msuf|open msuf|open options|open addon options|slash command|/msuf|msuf menu|where is options|addon options|config menu|configuration menu|settings menu	700
        ]])
    end)
end
